### ISSUE TITLE
Plans to Release the Remaining 1600 hours?

### ISSUE THREAD

**Issue by snakers4** [sovaai/sova-dataset#1]
> Таким образом у нас накопилась база в 1700+ часов
> https://habr.com/ru/company/ashmanov_net/blog/523412/
> At the moment, the total length of the audio is 102 hours, the ratio of male and female voices ~50/50.

Hi,

Are you going to release the remaining 1600 hours?

**Comment by ZubarevEgor** [comment]
Hi @snakers4 

We are planning to release 10,000 hours (rus/eng) in December 2020.

**Comment by snakers4** [comment]
> We are planning to release 10,000 hours (rus/eng) in December 2020.

Any preliminary hints on:

- how much data per language / domain
- annotation type / quality
- license

?

**Comment by ZubarevEgor** [comment]
@snakers4 sure, i can post some:

- language proportion around 20% Russian and rest English / Audiobooks and Phone calls (various topics)
- Forced alignment (books) + manual (books + calls) / ~95%
- probably CC BY 4.0

**Comment by snakers4** [comment]
I see 
Thanks
